### ISSUE TITLE
Installation failing because Openstack image already exists

### ISSUE THREAD

**Issue by fgiorgetti** [redhat-cop/osia#21]
Although logs say it is reusing the image, the installation fails.
If I remove the image from my openstack tenant and retry, it works.

2021-04-19 14:18:01 jenkins-slave root[3156] INFO Reusing found image in openstack osia-rhcos-47.83.202102090044-0
Traceback (most recent call last):
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/osia/installer/clouds/openstack.py", line 210, in resolve_image
    add_cluster(osp_connection, image, cluster_name)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/osia/installer/clouds/openstack.py", line 145, in add_cluster
    osp_connection.image.update_image(image, osia_clusters=','.join(clusters))
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/image/v2/_proxy.py", line 516, in update_image
    return self._update(_image.Image, image, **attrs)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/proxy.py", line 47, in check
    return method(self, expected, actual, *args, **kwargs)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/proxy.py", line 435, in _update
    return res.commit(self, base_path=base_path)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/resource.py", line 1543, in commit
    retry_on_conflict=retry_on_conflict)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/resource.py", line 1569, in _commit
    self._translate_response(response, has_body=has_body)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/resource.py", line 1158, in _translate_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/home/cloud-user/.local/share/virtualenvs/ocp4-configuration-b4-2WUz_/lib/python3.6/site-packages/openstack/exceptions.py", line 235, in raise_from_response
    http_status=http_status, request_id=request_id
openstack.exceptions.ConflictException: ConflictException: 409: Client Error for url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13292/v2/images/39513c9f-9035-49ef-8119-aa52b03b6054, Conflict

**Comment by mdujava** [comment]
~~resolved via https://github.com/redhat-cop/osia/pull/28/files~~
This looks like is an issue with the update of the metadata of the image, which is read-only afaik.

**Comment by mijaros** [comment]
@fgiorgetti This is unfortunate problem of the openstack instance you are using. AFAIK this is not the problem necesairly of osia, but that for unknown reason the openstack doesn't allow modification of object labels. 

The core concept which osia follows is that anything it does it will also clean. 

You have then two options:
- use `osp-image-unique` which uploads separate image per instance - this option was implemented for this precise situation.
- upload the image yourself and then use `osp-image` which will use it directly without taking ownership.
