### ISSUE TITLE
Osia errors out after succesfully installing cluster

### ISSUE THREAD

**Issue by mkrutov** [redhat-cop/osia#4]
Log snip:
```

INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=<kubeconfig>'
INFO Access the OpenShift web-console here: <url> 
INFO Login to the console with user: "kubeadmin", and password: "<password>" 
INFO Time elapsed: 32m37s                         
Traceback (most recent call last):
  File "/usr/local/bin/osia", line 11, in <module>
    load_entry_point('osia==0.2.0', 'console_scripts', 'osia')()
  File "/usr/local/lib/python3.6/site-packages/osia-0.2.0-py3.6.egg/osia/cli.py", line 211, in main_cli
  File "/usr/local/lib/python3.6/site-packages/osia-0.2.0-py3.6.egg/osia/cli.py", line 130, in _exec_install_cluster
  File "/usr/local/lib/python3.6/site-packages/osia-0.2.0-py3.6.egg/osia/installer/executor.py", line 78, in install_cluster
  File "/usr/local/lib/python3.6/site-packages/osia-0.2.0-py3.6.egg/osia/installer/clouds/openstack.py", line 144, in post_installation
  File "/usr/local/lib/python3.6/site-packages/osia-0.2.0-py3.6.egg/osia/installer/clouds/openstack.py", line 81, in _attach_fip_to_port
  File "/usr/local/lib/python3.6/site-packages/openstack/network/v2/_proxy.py", line 1820, in add_ip_to_port
    ip.port_id = port.id
AttributeError: 'NoneType' object has no attribute 'port_id'
```

**Comment by mijaros** [comment]
Found the bug, it was a typo after linter run.
